###############
# diploid set #
###############

mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Chi_DB /path_to_output/230927_pairs/out__Ath_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Chi_DB /path_to_output/230927_pairs/out__Ath_vs_Chi  /path_to_output/230927_pairs/out__Ath_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Cru_DB /path_to_output/230927_pairs/out__Ath_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Cru_DB /path_to_output/230927_pairs/out__Ath_vs_Cru  /path_to_output/230927_pairs/out__Ath_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Tar_DB /path_to_output/230927_pairs/out__Ath_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Tar_DB /path_to_output/230927_pairs/out__Ath_vs_Tar  /path_to_output/230927_pairs/out__Ath_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Aar_DB /path_to_output/230927_pairs/out__Ath_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Aar_DB /path_to_output/230927_pairs/out__Ath_vs_Aar  /path_to_output/230927_pairs/out__Ath_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Ath_DB /path_to_output/230927_pairs/out__Chi_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Ath_DB /path_to_output/230927_pairs/out__Chi_vs_Ath  /path_to_output/230927_pairs/out__Chi_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Cru_DB /path_to_output/230927_pairs/out__Chi_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Cru_DB /path_to_output/230927_pairs/out__Chi_vs_Cru  /path_to_output/230927_pairs/out__Chi_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Tar_DB /path_to_output/230927_pairs/out__Chi_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Tar_DB /path_to_output/230927_pairs/out__Chi_vs_Tar  /path_to_output/230927_pairs/out__Chi_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Aar_DB /path_to_output/230927_pairs/out__Chi_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Aar_DB /path_to_output/230927_pairs/out__Chi_vs_Aar  /path_to_output/230927_pairs/out__Chi_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Ath_DB /path_to_output/230927_pairs/out__Cru_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Ath_DB /path_to_output/230927_pairs/out__Cru_vs_Ath  /path_to_output/230927_pairs/out__Cru_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Chi_DB /path_to_output/230927_pairs/out__Cru_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Chi_DB /path_to_output/230927_pairs/out__Cru_vs_Chi  /path_to_output/230927_pairs/out__Cru_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Tar_DB /path_to_output/230927_pairs/out__Cru_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Tar_DB /path_to_output/230927_pairs/out__Cru_vs_Tar  /path_to_output/230927_pairs/out__Cru_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Aar_DB /path_to_output/230927_pairs/out__Cru_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Aar_DB /path_to_output/230927_pairs/out__Cru_vs_Aar  /path_to_output/230927_pairs/out__Cru_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Ath_DB /path_to_output/230927_pairs/out__Tar_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Ath_DB /path_to_output/230927_pairs/out__Tar_vs_Ath  /path_to_output/230927_pairs/out__Tar_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Chi_DB /path_to_output/230927_pairs/out__Tar_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Chi_DB /path_to_output/230927_pairs/out__Tar_vs_Chi  /path_to_output/230927_pairs/out__Tar_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Cru_DB /path_to_output/230927_pairs/out__Tar_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Cru_DB /path_to_output/230927_pairs/out__Tar_vs_Cru  /path_to_output/230927_pairs/out__Tar_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Aar_DB /path_to_output/230927_pairs/out__Tar_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Aar_DB /path_to_output/230927_pairs/out__Tar_vs_Aar  /path_to_output/230927_pairs/out__Tar_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Ath_DB /path_to_output/230927_pairs/out__Aar_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Ath_DB /path_to_output/230927_pairs/out__Aar_vs_Ath  /path_to_output/230927_pairs/out__Aar_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Chi_DB /path_to_output/230927_pairs/out__Aar_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Chi_DB /path_to_output/230927_pairs/out__Aar_vs_Chi  /path_to_output/230927_pairs/out__Aar_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Cru_DB /path_to_output/230927_pairs/out__Aar_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Cru_DB /path_to_output/230927_pairs/out__Aar_vs_Cru  /path_to_output/230927_pairs/out__Aar_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Tar_DB /path_to_output/230927_pairs/out__Aar_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Tar_DB /path_to_output/230927_pairs/out__Aar_vs_Tar  /path_to_output/230927_pairs/out__Aar_vs_Tar.txt  --format-mode 2 

#####################
# higher ploidy set #
#####################

mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Ath_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Ath_vs_Chi  /path_to_output/230214_pairs/out__Ath_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Ath_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Ath_vs_Cru  /path_to_output/230214_pairs/out__Ath_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Ath_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Ath_vs_Tar  /path_to_output/230214_pairs/out__Ath_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Ath_vs_Bra  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Ath_vs_Bra  /path_to_output/230214_pairs/out__Ath_vs_Bra.txt  --format-mode 2 
mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Ath_vs_Csa  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Ath_vs_Csa  /path_to_output/230214_pairs/out__Ath_vs_Csa.txt  --format-mode 2 
mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Ath_vs_Sal  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Ath_vs_Sal  /path_to_output/230214_pairs/out__Ath_vs_Sal.txt  --format-mode 2 
mmseqs search /path_to_species_database/Ath_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Ath_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Ath_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Ath_vs_Aar  /path_to_output/230214_pairs/out__Ath_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Chi_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Chi_vs_Ath  /path_to_output/230214_pairs/out__Chi_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Chi_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Chi_vs_Cru  /path_to_output/230214_pairs/out__Chi_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Chi_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Chi_vs_Tar  /path_to_output/230214_pairs/out__Chi_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Chi_vs_Bra  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Chi_vs_Bra  /path_to_output/230214_pairs/out__Chi_vs_Bra.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Chi_vs_Csa  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Chi_vs_Csa  /path_to_output/230214_pairs/out__Chi_vs_Csa.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Chi_vs_Sal  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Chi_vs_Sal  /path_to_output/230214_pairs/out__Chi_vs_Sal.txt  --format-mode 2 
mmseqs search /path_to_species_database/Chi_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Chi_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Chi_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Chi_vs_Aar  /path_to_output/230214_pairs/out__Chi_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Cru_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Cru_vs_Ath  /path_to_output/230214_pairs/out__Cru_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Cru_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Cru_vs_Chi  /path_to_output/230214_pairs/out__Cru_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Cru_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Cru_vs_Tar  /path_to_output/230214_pairs/out__Cru_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Cru_vs_Bra  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Cru_vs_Bra  /path_to_output/230214_pairs/out__Cru_vs_Bra.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Cru_vs_Csa  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Cru_vs_Csa  /path_to_output/230214_pairs/out__Cru_vs_Csa.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Cru_vs_Sal  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Cru_vs_Sal  /path_to_output/230214_pairs/out__Cru_vs_Sal.txt  --format-mode 2 
mmseqs search /path_to_species_database/Cru_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Cru_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Cru_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Cru_vs_Aar  /path_to_output/230214_pairs/out__Cru_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Tar_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Tar_vs_Ath  /path_to_output/230214_pairs/out__Tar_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Tar_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Tar_vs_Chi  /path_to_output/230214_pairs/out__Tar_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Tar_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Tar_vs_Cru  /path_to_output/230214_pairs/out__Tar_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Tar_vs_Bra  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Tar_vs_Bra  /path_to_output/230214_pairs/out__Tar_vs_Bra.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Tar_vs_Csa  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Tar_vs_Csa  /path_to_output/230214_pairs/out__Tar_vs_Csa.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Tar_vs_Sal  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Tar_vs_Sal  /path_to_output/230214_pairs/out__Tar_vs_Sal.txt  --format-mode 2 
mmseqs search /path_to_species_database/Tar_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Tar_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Tar_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Tar_vs_Aar  /path_to_output/230214_pairs/out__Tar_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Bra_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Bra_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Bra_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Bra_vs_Ath  /path_to_output/230214_pairs/out__Bra_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Bra_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Bra_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Bra_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Bra_vs_Chi  /path_to_output/230214_pairs/out__Bra_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Bra_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Bra_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Bra_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Bra_vs_Cru  /path_to_output/230214_pairs/out__Bra_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Bra_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Bra_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Bra_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Bra_vs_Tar  /path_to_output/230214_pairs/out__Bra_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Bra_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Bra_vs_Csa  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Bra_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Bra_vs_Csa  /path_to_output/230214_pairs/out__Bra_vs_Csa.txt  --format-mode 2 
mmseqs search /path_to_species_database/Bra_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Bra_vs_Sal  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Bra_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Bra_vs_Sal  /path_to_output/230214_pairs/out__Bra_vs_Sal.txt  --format-mode 2 
mmseqs search /path_to_species_database/Bra_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Bra_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Bra_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Bra_vs_Aar  /path_to_output/230214_pairs/out__Bra_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Csa_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Csa_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Csa_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Csa_vs_Ath  /path_to_output/230214_pairs/out__Csa_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Csa_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Csa_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Csa_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Csa_vs_Chi  /path_to_output/230214_pairs/out__Csa_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Csa_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Csa_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Csa_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Csa_vs_Cru  /path_to_output/230214_pairs/out__Csa_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Csa_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Csa_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Csa_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Csa_vs_Tar  /path_to_output/230214_pairs/out__Csa_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Csa_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Csa_vs_Bra  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Csa_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Csa_vs_Bra  /path_to_output/230214_pairs/out__Csa_vs_Bra.txt  --format-mode 2 
mmseqs search /path_to_species_database/Csa_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Csa_vs_Sal  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Csa_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Csa_vs_Sal  /path_to_output/230214_pairs/out__Csa_vs_Sal.txt  --format-mode 2 
mmseqs search /path_to_species_database/Csa_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Csa_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Csa_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Csa_vs_Aar  /path_to_output/230214_pairs/out__Csa_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Sal_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Sal_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Sal_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Sal_vs_Ath  /path_to_output/230214_pairs/out__Sal_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Sal_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Sal_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Sal_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Sal_vs_Chi  /path_to_output/230214_pairs/out__Sal_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Sal_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Sal_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Sal_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Sal_vs_Cru  /path_to_output/230214_pairs/out__Sal_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Sal_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Sal_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Sal_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Sal_vs_Tar  /path_to_output/230214_pairs/out__Sal_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Sal_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Sal_vs_Bra  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Sal_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Sal_vs_Bra  /path_to_output/230214_pairs/out__Sal_vs_Bra.txt  --format-mode 2 
mmseqs search /path_to_species_database/Sal_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Sal_vs_Csa  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Sal_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Sal_vs_Csa  /path_to_output/230214_pairs/out__Sal_vs_Csa.txt  --format-mode 2 
mmseqs search /path_to_species_database/Sal_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Sal_vs_Aar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Sal_DB /path_to_species_database/Aar_DB /path_to_output/230214_pairs/out__Sal_vs_Aar  /path_to_output/230214_pairs/out__Sal_vs_Aar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Aar_vs_Ath  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Ath_DB /path_to_output/230214_pairs/out__Aar_vs_Ath  /path_to_output/230214_pairs/out__Aar_vs_Ath.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Aar_vs_Chi  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Chi_DB /path_to_output/230214_pairs/out__Aar_vs_Chi  /path_to_output/230214_pairs/out__Aar_vs_Chi.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Aar_vs_Cru  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Cru_DB /path_to_output/230214_pairs/out__Aar_vs_Cru  /path_to_output/230214_pairs/out__Aar_vs_Cru.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Aar_vs_Tar  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Tar_DB /path_to_output/230214_pairs/out__Aar_vs_Tar  /path_to_output/230214_pairs/out__Aar_vs_Tar.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Aar_vs_Bra  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Bra_DB /path_to_output/230214_pairs/out__Aar_vs_Bra  /path_to_output/230214_pairs/out__Aar_vs_Bra.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Aar_vs_Csa  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Csa_DB /path_to_output/230214_pairs/out__Aar_vs_Csa  /path_to_output/230214_pairs/out__Aar_vs_Csa.txt  --format-mode 2 
mmseqs search /path_to_species_database/Aar_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Aar_vs_Sal  /path_to_tmp/tmp --max-seqs 10
mmseqs convertalis /path_to_species_database/Aar_DB /path_to_species_database/Sal_DB /path_to_output/230214_pairs/out__Aar_vs_Sal  /path_to_output/230214_pairs/out__Aar_vs_Sal.txt  --format-mode 2 

